import 'package:pro_image_editor/pro_image_editor.dart';

/// Italian labels for `pro_image_editor`.
///
/// The package ships English defaults and has no Italian locale, so every
/// visible label is translated here. The app is Italian-only: an English
/// toolbar inside it would be the one screen that breaks the illusion.
///
/// Filter names (Aden, Amaro, Lo-Fi…) stay as they are — they are proper
/// names, not words to translate.
const ProImageEditorConfigs italianImageEditor = ProImageEditorConfigs(
  i18n: I18n(
    cancel: 'Annulla',
    undo: 'Annulla',
    redo: 'Ripeti',
    done: 'Fatto',
    remove: 'Rimuovi',
    doneLoadingMsg: 'Applicazione delle modifiche…',
    importStateHistoryMsg: 'Apertura dell\'editor…',
    various: I18nVarious(
      loadingDialogMsg: 'Attendere…',
      closeEditorWarningTitle: 'Chiudere l\'editor?',
      closeEditorWarningMessage: 'Le modifiche non salvate andranno perse.',
      closeEditorWarningConfirmBtn: 'Chiudi',
      closeEditorWarningCancelBtn: 'Continua a modificare',
    ),
    paintEditor: I18nPaintEditor(
      bottomNavigationBarText: 'Disegna',
      moveAndZoom: 'Sposta',
      freestyle: 'Mano libera',
      freestyleArrowStart: 'Freccia iniziale',
      freestyleArrowEnd: 'Freccia finale',
      freestyleArrowStartEnd: 'Freccia doppia',
      arrow: 'Freccia',
      line: 'Linea',
      rectangle: 'Rettangolo',
      circle: 'Cerchio',
      dashLine: 'Linea tratteggiata',
      dashDotLine: 'Linea punto-tratto',
      hexagon: 'Esagono',
      polygon: 'Poligono',
      blur: 'Sfoca',
      pixelate: 'Pixel',
      lineWidth: 'Spessore',
      eraser: 'Gomma',
      toggleFill: 'Riempimento',
      changeOpacity: 'Opacità',
      undo: 'Annulla',
      redo: 'Ripeti',
      done: 'Fatto',
      back: 'Indietro',
      smallScreenMoreTooltip: 'Altro',
      opacity: 'Opacità',
      color: 'Colore',
      strokeWidth: 'Spessore',
      fill: 'Riempimento',
      cancel: 'Annulla',
    ),
    textEditor: I18nTextEditor(
      inputHintText: 'Scrivi il testo',
      bottomNavigationBarText: 'Testo',
      back: 'Indietro',
      done: 'Fatto',
      textAlign: 'Allineamento',
      fontScale: 'Dimensione',
      backgroundMode: 'Sfondo',
      smallScreenMoreTooltip: 'Altro',
    ),
    cropRotateEditor: I18nCropRotateEditor(
      bottomNavigationBarText: 'Ritaglia e ruota',
      rotate: 'Ruota',
      flip: 'Capovolgi',
      tilt: 'Inclina',
      tiltRotate: 'Ruota',
      tiltHorizontal: 'Orizzontale',
      tiltVertical: 'Verticale',
      ratio: 'Proporzioni',
      back: 'Indietro',
      done: 'Fatto',
      cancel: 'Annulla',
      undo: 'Annulla',
      redo: 'Ripeti',
      smallScreenMoreTooltip: 'Altro',
      reset: 'Ripristina',
    ),
    tuneEditor: I18nTuneEditor(
      bottomNavigationBarText: 'Regola',
      back: 'Indietro',
      done: 'Fatto',
      brightness: 'Luminosità',
      contrast: 'Contrasto',
      saturation: 'Saturazione',
      exposure: 'Esposizione',
      hue: 'Tonalità',
      temperature: 'Temperatura',
      fade: 'Sbiadito',
      tint: 'Tinta',
      undo: 'Annulla',
      redo: 'Ripeti',
    ),
    filterEditor: I18nFilterEditor(
      bottomNavigationBarText: 'Filtri',
      back: 'Indietro',
      done: 'Fatto',
      filters: I18nFilters(none: 'Nessun filtro'),
    ),
    blurEditor: I18nBlurEditor(
      bottomNavigationBarText: 'Sfocatura',
      back: 'Indietro',
      done: 'Fatto',
    ),
    emojiEditor: I18nEmojiEditor(
      bottomNavigationBarText: 'Emoji',
      search: 'Cerca',
      categoryRecent: 'Recenti',
      categorySmileys: 'Faccine e persone',
      categoryAnimals: 'Animali e natura',
      categoryFood: 'Cibo e bevande',
      categoryActivities: 'Attività',
      categoryTravel: 'Viaggi e luoghi',
      categoryObjects: 'Oggetti',
      categorySymbols: 'Simboli',
      categoryFlags: 'Bandiere',
    ),
  ),
);
